version: "3"
services:
    api:
        image: middleware-api:latest
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        networks:
            - backend
            - traefik-public
        deploy:
          labels:
            - "traefik.enable=true"
            # change the host here
            - "traefik.http.routers.api.rule=Host(`api.kerbengenam.my.id`)"
            - "traefik.http.routers.api.entrypoints=web"
            - "traefik.http.services.api.loadbalancer.server.port=5000"

networks:
  backend:
  traefik-public:
    external: true
