version: '2'
services:
    api:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        networks:
            - backend
            - traefik-public
        deploy:
          labels:
            - "traefik.enable=true"
            # change the host here
            - "traefik.http.routers.api.rule=Host(`api.kerbengenam.my.id`)"
            - "traefik.http.routers.api.entrypoints=websecure"
            - "traefik.http.routers.api.tls=true"
            - "traefik.http.routers.api.tls.certresolver=leresolver"
            - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
            - "traefik.http.routers.api.middlewares=redirect-to-https@docker"
            - "traefik.http.services.api.loadbalancer.server.port=80"

networks:
  backend:
  traefik-public:
    external: true